### ISSUE TITLE
Failed to load model class 'XSmilesModel' from module 'xsmiles-ipywidget'

### ISSUE THREAD

**Issue by jessielyons** [Bayer-Group/xsmiles-jupyterlab#15]
Hi Xsmiles team,

I installed xmiles using "pip install xsmiles". And I get the error when I try running the "xsmiles.XSmilesWidget(molecules=json.dumps([molecule_with_sequence]))" as examples in your jupyter notebook.

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'XSmilesModel' from module 'xsmiles-ipywidget'
Error: Script error for "xsmiles-ipywidget"
http://requirejs.org/docs/errors.html#scripterror

Can you please also explain how/where to get the file you are recommending as alternate way to install xsmiles? How do I get the .whl file?
# You can install the latest official version from this repo with: 
# pip install xsmiles-0.2.2-py2.py3-none-any.whl

Attached please find the snapshot of error I received.

Thanks,
Jessie
<img width="1137" alt="Screen Shot 2023-08-04 at 5 29 56 PM" src="https://github.com/Bayer-Group/xsmiles-jupyterlab/assets/87676867/c91f228f-2f6d-4d58-808a-adf60a302fdd">

**Comment by heberleh** [comment]
I updated the Readme and maybe what I wrote in #16  may help you.
