### ISSUE TITLE
xsmiles_examples.ipynb <ValidationError: "Notebook could not be converted from version 1 to version 2 because it's missing a key: cells">

### ISSUE THREAD

**Issue by jessielyons** [Bayer-Group/xsmiles-jupyterlab#16]
Hey,

Also when I use command 
> jupyter lab xsmiles_examples.ipynb 

I get error:

xsmiles_examples.ipynb <ValidationError: "Notebook could not be converted from version 1 to version 2 because it's missing a key: cells">

So I have two error messages so far. Appreciate your help so I can try to use your great looking library.

**Comment by heberleh** [comment]
Hi @jessielyons, maybe a new version of JupyterLab is breaking it. It seems it's trying to convert notebook types.

I recreated both pip and conda venv and installed everything again, and I was able to run the notebook from this repository. I use the Chrome web-browser, and specified the versions as stated now in the Readme.

Try a fresh environment following the new instructions, with a new name for the virtual environment, so you make sure it's a fresh new environment:

I updated the Pip instructions:
```bash
# tested with python 3.9
python3.9 -m venv xsmiles_env
# activate env
source ./xsmiles_env/bin/activate

pip install xsmiles

# install dependencies for the example notebook
pip install jupyterlab==3.4.5 rdkit==2022.3.5 matplotlib==3.5.3 

jupyter lab examples/xsmiles_examples.ipynb
```

Or you can use conda:
```bash
conda create --name xsmiles_env python=3.9 jupyterlab=3.4.5 rdkit=2022.3.5 matplotlib=3.5.3 -c conda-forge

conda activate xsmiles_env # activate the created env

# You can install the latest official version from this repo with: 
# pip install xsmiles-0.2.2-py2.py3-none-any.whl
# Unofficial pypi xsmiles:
pip install xsmiles 

jupyter lab examples/xsmiles_examples.ipynb # run a notebook with jupyter lab
```

**Comment by heberleh** [comment]
Please note that I updated the environment to use Python 3.9 and it worked.

Python 3.7 was also working fine, as done in the Use Cases from the article (https://github.com/Bayer-Group/xsmiles-use-cases). For those notebooks, Python 3.7 is necessary:

> Make sure tensorboard==1.13.1 and tensorflow==1.13.2 were installed correctly through requirements.txt, CDDD depends on them, as well as on python <= 3.7.

**Comment by jessielyons** [comment]
Hi @heberleh ,

Many thanks. Using the method of creating a new conda environment works. I will continue to explore and may reach back with any other questions.

Cheers,
JL
