### ISSUE TITLE
demo website is not working?

### ISSUE THREAD

**Issue by ghost** [Bayer-Group/xsmiles-jupyterlab#3]
I tried to use both Safari and Chrome to visit the demo website. https://bayer-group.github.io/xsmiles/dist/web/
In both cases, I cannot see anything.

**Comment by heberleh** [comment]
I will try again, but it was working on working, MacBook and Windows, and personal laptops on Edge and Chrome. However, a blank page appears for some seconds while it downloads some libraries and render the molecules. What did it show for you? What’s your computer config?
The website is not intended for phone, but I tried it now on safari in an iPhone and it loaded at least. Maybe wait a bit more or check firewalls?

**Comment by ghost** [comment]
Thanks! I just tried and it's working now!
